name: Deploy OurChants via Makefile

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  CF_DISTRO_ID: ${{ secrets.CF_DISTRO_ID }}
  API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Checkout code
      uses: actions/checkout@v4

    - name: 🟢 Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::418272766513:role/github-actions-ourchants-deploy
        aws-region: ${{ env.AWS_REGION }}

    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: 💾 Install dependencies
      run: npm ci

    - name: 🔄 Fetch latest stack configuration
      run: |
        # Get API endpoint from ApiStack
        API_ENDPOINT=$(aws cloudformation describe-stacks \
          --stack-name "ApiStack" \
          --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
          --output text)
        
        # Get CloudFront distribution ID from OurChantsFrontendStack
        CF_DISTRO_ID=$(aws cloudformation describe-stack-resources \
          --stack-name "OurChantsFrontendStack" \
          --query "StackResources[?ResourceType=='AWS::CloudFront::Distribution'].PhysicalResourceId | [0]" \
          --output text)
        
        # Get S3 bucket name from CloudFront distribution
        BUCKET_NAME=$(aws cloudfront get-distribution-config \
          --id "$CF_DISTRO_ID" \
          --query "DistributionConfig.Origins.Items[0].DomainName" \
          --output text | sed 's|.s3-website-us-east-1.amazonaws.com||')
        
        # Get domain name from OurChantsFrontendStack
        DOMAIN_NAME=$(aws cloudformation describe-stacks \
          --stack-name "OurChantsFrontendStack" \
          --query "Stacks[0].Parameters[?ParameterKey=='DomainName'].ParameterValue | [0]" \
          --output text)
        
        # Export for use in subsequent steps
        echo "API_ENDPOINT=$API_ENDPOINT" >> $GITHUB_ENV
        echo "CF_DISTRO_ID=$CF_DISTRO_ID" >> $GITHUB_ENV
        echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
        echo "DOMAIN_NAME=$DOMAIN_NAME" >> $GITHUB_ENV

    - name: 🧪 Inject build-time secrets into .env
      run: |
        echo "API_ENDPOINT=${API_ENDPOINT}" >> .env
        echo "DOMAIN_NAME=${DOMAIN_NAME}" >> .env

    - name: 🚀 Run full deployment
      run: make deploy 